version: '3.7'

services:
  minio:
    container_name: minio
    env_file: .env
    image: quay.io/minio/minio:RELEASE.2024-02-13T15-35-11Z
    command: server /data --console-address ":${WEB_PORT_MINIO:?}"
    hostname: minio
    ports:
      - "${API_PORT_MINIO:?}:${API_PORT_MINIO:?}"
      - "${WEB_PORT_MINIO:?}:${WEB_PORT_MINIO:?}"
    expose:
      - ${API_PORT_MINIO:?}
      - ${WEB_PORT_MINIO:?}
    volumes:
      - ./data-minio/:/data
    environment:
      MINIO_ROOT_USER: ${MINIO_USER:?}
      MINIO_ROOT_PASSWORD: ${MINIO_PASSWORD:?}
    networks:
      - s3


networks:
  s3:
    driver: bridge
